export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";




export const CATEGORY_FETCH_REQUEST = "CATEGORY_FETCH_REQUEST";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";