export const NEW_POST_REQUEST = "NEW_POST_REQUEST"; 
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS"; 
export const NEW_POST_FAIL = "NEW_POST_FAIL"; 



export const POST_FETCH_REQUEST = "POST_FETCH_REQUEST";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_FAIL = "POST_FETCH_FAIL";




export const SINGLE_POST_FETCH_REQUEST = "SINGLE_POST_FETCH_REQUEST";
export const SINGLE_POST_FETCH_SUCCESS = "SINGLE_POST_FETCH_SUCCESS";
export const SINGLE_POST_FETCH_FAIL = "SINGLE_POST_FETCH_FAIL";




export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";

